name: deploy

run-name: ${{ github.actor }} is starting github actions

on:
  push

jobs:
  my_first_job:
    runs-on: ubuntu-latest
    name: Build, Test, and Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build the solution
        run: dotnet build --no-restore --configuration Release

      - name: Run tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      - name: Publish application
        run: |
          dotnet publish -c Release -o ./publish